— Text Vectorization (Part 1: Classic Methods)

In [ ]:
# 1. Why Text Needs Numeric Representation
# Machine learning models only understand numbers. They cannot read text directly.
# So we must convert our cleaned text into numeric form.
# This process is called Text Vectorization or Feature Extraction.

# Example: 'I love cricket' cannot be fed to a model. It must become something like [0, 1, 0, 1, 1, 0].


In [ ]:
# ML models are like calculators — they only understand numbers. "I love NLP" means nothing to a model.
# But [1, 0, 1, 0, 0, 1] — a vector — does.
# Text vectorization = converting words into numbers the model can compute with.

# Words - Numbers - ML Model can learn

# text  = "I love NLP"
# vectorize
# vector = [1, 0, 1, 0, 1]   # each position = one word in vocab

# Machine learning models work on vectors, not strings
# Every NLP pipeline starts with this conversion

# the pipeline
# Raw Text - Tokenize - Vectorize - ML Model

In [ ]:
# 2. Bag of Words (BoW)
# Bag of Words is the simplest method to convert text into numbers.
# The idea is: represent each document by counting how many times each word appears.
# Order of words does not matter — just count the frequency.

# How BoW Works — Step by Step
# Step 1 — Collect all unique words from all documents. This is your Vocabulary.
# Step 2 — For each document, count how many times each vocabulary word appears.
# Step 3 — Each document becomes a vector (row of numbers).

# Example: Doc1: 'I love cricket'   Doc2: 'I love football'
# Example: Vocabulary: [I, love, cricket, football]
# Example: Doc1 vector: [1, 1, 1, 0]   Doc2 vector: [1, 1, 0, 1]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

docs = [
    "I love NLP",
    "I love Python",
    "NLP is fun"
]

cv = CountVectorizer()
X = cv.fit_transform(docs)

print(cv.get_feature_names_out())
print(X.toarray())
# Each row = 1 document, each column = 1 word
# Value = how many times that word appears


# output — the BoW matrix
#          fun	is	love   nlp	python
# doc 1	    0	0	1	   1	0
# doc 2	    0	0	1	   0	1
# doc 3	    1	1	0	   1	0

# BoW treats a document as an unordered bag of words.
# "I love NLP" and "NLP love I" give the same vector.
# It ignores word order and grammar — but it works surprisingly well for classification tasks like spam detection.

# simple & fast, ignores word order ,common words dominate

['fun' 'is' 'love' 'nlp' 'python']
[[0 0 1 1 0]
 [0 0 1 0 1]
 [1 1 0 1 0]]


In [ ]:
# Advantages of BoW
# Very simple and easy to understand.
# Fast to compute even on large datasets.
# Works well for basic text classification tasks.

# Limitations of BoW
# Word order is ignored — 'I love NLP' and 'NLP love I' give same vector.
# No meaning is captured — just counts.
# Common words like 'the', 'is' get high counts but carry no meaning.
# Vocabulary size can be huge — creates very large sparse matrices.


In [ ]:
# 3. N-grams
# N-grams are combinations of N consecutive words treated as a single unit.
# They help capture some context that BoW misses.

# Types of N-grams
# Unigram (N=1) — Single words. Example: 'love', 'cricket', 'is'
# Bigram (N=2) — Pairs of consecutive words. Example: 'love cricket', 'is good'
# Trigram (N=3) — Groups of 3 consecutive words. Example: 'I love cricket'

# Example: Sentence: 'I love cricket'
# Example: Unigrams: [I, love, cricket]
# Example: Bigrams: [I love, love cricket]
# Example: Trigrams: [I love cricket]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

text = ["I love NLP and Python"]

# Unigram (1 word at a time) — default
uni = CountVectorizer(ngram_range=(1,1))
print(uni.fit_transform(text).toarray())
# ['and', 'love', 'nlp', 'python'] each separately

# Bigram (2 words at a time)
bi = CountVectorizer(ngram_range=(2,2))
print(bi.fit(text).get_feature_names_out())
# ['and python', 'i love', 'love nlp', 'nlp and']

# Trigram (3 words at a time)
tri = CountVectorizer(ngram_range=(3,3))
print(tri.fit(text).get_feature_names_out())
# ['i love nlp', 'love nlp and', 'nlp and python']

# output
# Unigrams:  ['and', 'love', 'nlp', 'python']
# Bigrams:   ['and python', 'i love', 'love nlp', 'nlp and']
# Trigrams:  ['i love nlp', 'love nlp and', 'nlp and python']
# N-grams preserve context that BoW loses. "not good" as a bigram captures negative sentiment — BoW would just see "not" and "good" separately. Use ngram_range=(1,2) to get both unigrams and bigrams together.

# captures word order context, vocabulary grows fast with n, best: ngram_range=(1,2)

[[1 1 1 1]]
['and python' 'love nlp' 'nlp and']
['love nlp and' 'nlp and python']


In [ ]:
# Why Bigrams Improve Context
# 'not good' as a bigram captures negative sentiment correctly.
# Using just unigrams: 'not' and 'good' are separate — model may think it is positive.
# Bigrams keep these words together and preserve their combined meaning.

# In practice, using unigrams + bigrams together gives better results than using unigrams alone.


In [ ]:
# 4. TF-IDF — Term Frequency Inverse Document Frequency
# TF-IDF is a smarter way to represent text compared to plain BoW.
# Instead of just counting words, it gives importance score to each word.
# Words that appear too often in all documents (like 'the', 'is') get a low score.
# Words that are rare and unique to specific documents get a high score.


In [ ]:
# TF — Term Frequency
# TF measures how often a word appears in ONE document.
# If a word appears many times in a document, its TF is high.
# Example: If 'cricket' appears 5 times in a 100-word document: TF = 5/100 = 0.05

# IDF — Inverse Document Frequency
# IDF measures how rare or common a word is across ALL documents.
# If a word appears in almost every document, IDF is low (it is common, not useful).
# If a word appears in very few documents, IDF is high (it is special and informative).
# Example: 'the' appears in all 1000 documents - IDF is very low.
# Example: 'blockchain' appears in only 10 documents - IDF is very high.

# TF-IDF Final Score
# TF-IDF score = TF * IDF.
# High score means: word appears often in this document AND is rare overall.
# Low score means: word is very common across all documents (not important).

# TF-IDF automatically reduces the weight of common words and highlights important, document-specific words.
# This makes it much better than plain BoW.


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

docs = [
    "I love NLP",
    "I love Python",
    "NLP is really fun and really great"
]

tfidf = TfidfVectorizer()
X = tfidf.fit_transform(docs)

print(tfidf.get_feature_names_out())
print(X.toarray().round(2))

# TF  = how often a word appears in THIS document
# IDF = how rare that word is across ALL documents
# TF-IDF = TF × IDF  (rare + frequent = high score)

# output — scores (higher = more important)
#           fun	    love	nlp	   python	really
# doc 1	    0.00	0.51	0.51	0.00	0.00
# doc 2	    0.00	0.51	0.00	0.86	0.00
# doc 3	    0.42	0.00	0.28	0.00	0.84
# TF-IDF solves BoW's biggest problem: common words like "the", "is", "I" appear everywhere and dominate BoW scores.
# TF-IDF downweights them automatically — words unique to a document get higher scores. Much better for search and classification.

# rewards rare, meaningful words, punishes common filler words, go-to for text classification

['and' 'fun' 'great' 'is' 'love' 'nlp' 'python' 'really']
[[0.   0.   0.   0.   0.71 0.71 0.   0.  ]
 [0.   0.   0.   0.   0.61 0.   0.8  0.  ]
 [0.34 0.34 0.34 0.34 0.   0.26 0.   0.68]]


In [ ]:
# Why TF-IDF is Better than BoW
# BoW gives 'the' a high count — but 'the' is useless for ML.
# TF-IDF gives 'the' a near-zero score automatically.
# TF-IDF highlights words that are truly important for each document.


In [ ]:
# 5. Sparse Matrices
# When you create BoW or TF-IDF matrices, most values are zero.
# If vocabulary has 10,000 words and a document has only 50 unique words, 9,950 values are zero.
# Such a matrix with mostly zeros is called a Sparse Matrix.

# Sparse matrices take a lot of memory if stored normally.
# Libraries like scipy store only the non-zero values to save memory.
# This is called Sparse Matrix format — efficient and fast.

# This is a limitation of BoW and TF-IDF.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import scipy.sparse as sp

docs = ["I love NLP", "Python is great", "NLP is fun"]

cv = CountVectorizer()
X = cv.fit_transform(docs)   # returns sparse matrix by default

print("Type:",    type(X))
print("Shape:",   X.shape)
print("Stored:",  X.nnz,    "non-zero values")
print("Total:",   X.shape[0] * X.shape[1], "total cells")

# Convert to dense only when you need to inspect it
dense = X.toarray()
print(dense)

# output
# Type:    <class 'scipy.sparse._csr.csr_matrix'>
# Shape:   (3, 6)           - 3 docs, 6 unique words
# Stored:  7 non-zero values
# Total:   18 total cells   - only 7 of 18 are non-zero!

# [[0 1 0 1 0 0]
#  [0 0 1 0 1 1]
#  [1 0 1 1 0 0]]
# Real datasets have 50,000+ words in vocab. Each document uses maybe 200.
# Storing all those zeros wastes huge memory. Sparse matrices only store the non-zero values —
# a 10,000 × 50,000 matrix that's 99% zeros uses almost no RAM.
# Always keep it sparse until you absolutely need .toarray().

# memory efficient, sklearn outputs sparse by default, avoid .toarray() on large data  scipy.sparse handles it all

Type: <class 'scipy.sparse._csr.csr_matrix'>
Shape: (3, 6)
Stored: 8 non-zero values
Total: 18 total cells
[[0 0 0 1 1 0]
 [0 1 1 0 0 1]
 [1 0 1 0 1 0]]


In [ ]:
# Summary

# Built a Bag of Words matrix using CountVectorizer from sklearn.
# Built a TF-IDF matrix using TfidfVectorizer from sklearn.
# Visualized top words and their TF-IDF scores.
# Compared BoW vs TF-IDF output on same documents.
# Observed how TF-IDF gives lower scores to common words.

# CountVectorizer and TfidfVectorizer in scikit-learn are the standard tools.
# They handle everything from vocabulary creation to matrix building.

# 1 is the "why" — models need numbers, not strings.
# 2 (BoW) is the simplest way to get those numbers — just count words.
# 3 (N-grams) improves BoW by keeping word-order context like "not good".
# 4 (TF-IDF) improves BoW by weighting rare words higher than common ones.
# 5 (Sparse Matrix) is the behind-the-scenes data structure that makes all of the above memory-efficient.

— Text Vectorization (Part 2: Word Embeddings)

In [ ]:
# 1. What are Word Embeddings?
# Word embeddings are a smarter way to represent words as numbers.
# Instead of a big sparse vector (mostly zeros), each word gets a small dense vector (all numbers have meaning).
# The key feature: words with similar meaning get similar vectors.

# Example: 'king' and 'queen' will have vectors that are very close to each other in space.
# Example: 'cat' and 'dog' will be close. But 'cat' and 'airplane' will be far apart.

# BoW and TF-IDF treat every word as independent. Embeddings capture relationships and meaning between words.


In [ ]:
# BoW gives every word a slot in a huge sparse vector. Embeddings give every word a small dense vector —
# 100 to 300 numbers — where position in space encodes meaning. Similar words land near each other in this space.

# BoW vs embedding — same 3 words
# BoW — sparse, 10,000+ dimensions
# "king" -  0 0 1 0 0 0 0 … 9993 zeros

# Embedding — dense, 4 dims shown (real = 100–300)

# "king" -   0.82  -0.39  0.14  0.71 …
# "queen" -  0.79  -0.41  0.12  0.68 …
# "apple" - -0.11   0.55  0.89 -0.22 …
# Notice "king" and "queen" have nearly identical vectors. "apple" looks completely different.
# The model learned that kings and queens share context — royalty, power, gender — purely from reading text.

In [ ]:
# Dense vs Sparse Vectors
# BoW/TF-IDF: Sparse — vector size = vocabulary size (could be 50,000+), mostly zeros.
# Embeddings: Dense — vector size = 100 to 300, every value is meaningful.

# Example: BoW vector for 'dog': [0,0,0,1,0,0,0,...,0] — 50,000 dimensions, one '1'.
# Example: Embedding for 'dog': [0.23, -0.87, 0.45, 0.12, ...] — 300 dimensions, all meaningful.


In [ ]:
# 2. Word2Vec
# Word2Vec is a famous algorithm developed by Google in 2013.
# It trains a neural network to learn word embeddings from a large text corpus.
# The core idea: a word's meaning can be understood by looking at the words around it.


In [ ]:
from gensim.models import Word2Vec
# pip install gensim

sentences = [
    ["the", "king", "rules", "the", "kingdom"],
    ["the", "queen", "rules", "the", "palace"],
    ["the", "man", "is", "strong"],
    ["the", "woman", "is", "strong"],
]

model = Word2Vec(
    sentences,
    vector_size=50,   # 50-dim vector per word
    window=3,         # context window size
    min_count=1,      # include words seen ≥1 time
    epochs=100        # training passes
)

# Get vector for a word
vec = model.wv["king"]
print(vec.shape)          # (50,)

# Find most similar words
print(model.wv.most_similar("king", topn=3))

# Word2Vec trains a shallow neural net to predict a word from its neighbours (or vice versa).
# The hidden layer weights become the word vectors.
# Two architectures: CBOW (predict word from context) and Skip-gram (predict context from word). Skip-gram works better for rare words.

# vector_size: 50–300 typical, window: how much context to look at, needs large corpus to train well

(50,)
[('man', 0.2243129312992096), ('the', 0.09998968988656998), ('palace', 0.09006471931934357)]


In [ ]:
# CBOW — Continuous Bag of Words
# In CBOW, the model looks at surrounding words and tries to predict the center word.
# Example: Sentence: 'The cat sat on the mat'
# Example: Context: [The, sat, on, the] → Predict: 'cat'
# CBOW is faster and works better on larger datasets.
# syntax = Word2Vec(sentences, sg=0) #CBOW(default)

# Skip-Gram
# In Skip-Gram, the model takes one word and tries to predict surrounding context words.
# Example: Input: 'cat' - Predict: [The, sat, on, the]
# Skip-Gram works better on smaller datasets and rare words.
# syntax = Word2Vec(sentences, sg=a) #Skip-gram

# Both CBOW and Skip-Gram learn the same thing — word relationships. Just from opposite directions.


In [ ]:
# 3. GloVe — Global Vectors for Word Representation
# GloVe is another word embedding method developed by Stanford.
# While Word2Vec learns from local context (nearby words), GloVe also uses global word co-occurrence statistics across the entire corpus.

# GloVe combines the best of both local context and global statistics.
# It is pre-trained on very large text corpora.
# Results are very high quality, especially for general language tasks.

# Co-occurrence means: how often two words appear together in the same document across the whole dataset.


In [ ]:
# Word2Vec learns from local sliding windows. GloVe builds a giant co-occurrence matrix first —
# how often does every word appear near every other word across the entire corpus — then factorizes it. It sees the global picture.

import gensim.downloader as api

# Download GloVe trained on 6B tokens (Wikipedia + Gigaword)
glove = api.load("glove-wiki-gigaword-100")
# this downloads ~130 MB once, then caches it

# Get vector
vec = glove["python"]
print(vec.shape)               # (100,)

# Most similar words
print(glove.most_similar("python", topn=4))

# Cosine similarity between two words
sim = glove.similarity("king", "queen")
print(f"king - queen similarity: {sim:.2f}")

# glove-wiki-gigaword-50 (50d, lighter), glove-wiki-gigaword-100 (100d, balanced), glove-wiki-gigaword-300 (300d, best quality)

(100,)
[('monty', 0.6886237263679504), ('php', 0.586538553237915), ('perl', 0.5784407258033752), ('cleese', 0.5446676015853882)]
king - queen similarity: 0.75


In [ ]:
# 4. Why Embeddings Outperform BoW

# BoW: 'good' and 'great' are completely different words — no relation.
# Embeddings: 'good' and 'great' have very similar vectors — model understands they are related.

# BoW: Cannot understand synonyms, antonyms, or word relationships.
# Embeddings: Automatically capture semantic similarity.

# BoW: Sparse — very memory heavy.
# Embeddings: Dense — compact and efficient.


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import gensim.downloader as api

s1 = "I love dogs"
s2 = "I adore puppies"
# These mean almost the same thing!

# BoW: treats them as completely different
cv = CountVectorizer()
X = cv.fit_transform([s1, s2])
print("BoW vocab:", cv.get_feature_names_out())
# ['adore', 'dogs', 'love', 'puppies'] — zero overlap!

# Embeddings: understand they're related
glove = api.load("glove-wiki-gigaword-100")
print(glove.similarity("love",  "adore"))   # 0.76 (similar!)
print(glove.similarity("dogs",  "puppies")) # 0.82 (similar!)
print(glove.similarity("king",  "apple"))   # 0.11 (different!)

# BoW sees "love" and "adore" as completely unrelated — they share no characters.
# Embeddings know they're synonyms because they appear in the same contexts across millions of sentences. This is called semantic similarity.

BoW vocab: ['adore' 'dogs' 'love' 'puppies']
0.40220007
0.6315429
0.2667745


In [ ]:
# 5. Using Pre-trained Embeddings
# Training your own embeddings from scratch requires millions of documents and a lot of time.
# Instead, we can use embeddings that are already trained on huge datasets by researchers.

# Google News Word2Vec
# Trained on 100 billion words from Google News articles.
# Contains 3 million words and phrases.
# Each word has a 300-dimensional vector.

# GloVe Twitter
# GloVe embeddings trained on 2 billion tweets.
# Best for social media text analysis.
# Available in 25, 50, 100, and 200 dimensions.

# Always prefer pre-trained embeddings. They are trained on much more data than you have. You get high-quality word representations for free.


In [ ]:
# Training Word2Vec from scratch needs millions of sentences.
# Pre-trained embeddings are already trained on Wikipedia, news, Twitter etc.
# Just load and use — like using a GPU driver instead of writing one.

import gensim.downloader as api

# Available pre-trained models — pick one:
# "word2vec-google-news-300"   - 300d, trained on 100B Google News words
# "glove-wiki-gigaword-100"   - 100d, Wikipedia + Gigaword
# "fasttext-wiki-news-subwords-300" → handles unknown/misspelled words

model = api.load("glove-wiki-gigaword-100")

# 1. Get a word vector
vec = model["science"]          # shape: (100,)

# 2. Find nearest neighbours
print(model.most_similar("science", topn=5))

# 3. Check if word exists in vocab
print("physics" in model)        # True
print("xyzfoo"  in model)        # False - use .get() or try/except

# word2vec-google-news-300 - best general quality, glove-wiki-gigaword-100 - fast & balanced, fasttext - handles typos & rare words

[('sciences', 0.8073161244392395), ('physics', 0.7914698123931885), ('institute', 0.7663252353668213), ('mathematics', 0.7607672810554504), ('studies', 0.7590447664260864)]
True
False


In [ ]:
# 6. Representing Sentences Using Average Embeddings
# Word2Vec and GloVe give vectors for individual words, not whole sentences.
# To get a vector for a sentence, the simplest method is averaging.

# Take every word in the sentence.
# Get the embedding vector for each word.
# Take the average of all those vectors.
# The result is one vector that represents the whole sentence.

# Example: Sentence: 'dog runs fast' - vector(dog) + vector(runs) + vector(fast) divided by 3 = sentence vector

# Averaging loses word order. Better methods like sentence transformers exist.
# But average embeddings are a good simple starting point.


In [ ]:
# Word embeddings give a vector per word. But you often need a vector for a whole sentence.
# Simplest approach: average all the word vectors. One sentence = one vector.

import numpy as np
import gensim.downloader as api

model = api.load("glove-wiki-gigaword-100")

def sentence_vector(sentence, model):
    words = sentence.lower().split()
    vecs = [model[w] for w in words if w in model]
    if not vecs:
        return np.zeros(model.vector_size)
    return np.mean(vecs, axis=0)   # average all word vectors

s1 = "I love machine learning"
s2 = "I enjoy deep learning"
s3 = "The cat sat on the mat"

v1 = sentence_vector(s1, model)   # shape: (100,)
v2 = sentence_vector(s2, model)
v3 = sentence_vector(s3, model)

from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity([v1],[v2])[0][0].round(2)) # s1 = s2
print(cosine_similarity([v1],[v3])[0][0].round(2)) # s1 = s3

# Average pooling is simple but works well for sentence similarity, clustering, and search.
# For production, use sentence-transformers (BERT-based) which understands word order and context far better.

0.89
0.69


In [ ]:
# 7. The Famous Word Analogy Task
# One of the most impressive features of Word2Vec is its ability to do word analogies using vector arithmetic.

# 'king' - 'man' + 'woman' = 'queen'
# 'Paris' - 'France' + 'India' = 'Delhi'
# 'walked' - 'walk' + 'run' = 'ran'

# This works because embeddings capture relationships in vector space.
# The direction from 'man' to 'woman' is the same as the direction from 'king' to 'queen'.

# This analogy task proves that embeddings truly capture meaning and relationships — not just counts like BoW.

In [ ]:
# The most mind-blowing property of embeddings: vector arithmetic encodes relationships.
# "king − man + woman" lands near "queen". The model learned gender, royalty, geography — all from text patterns.

import gensim.downloader as api

model = api.load("glove-wiki-gigaword-100")

# king - man + woman = ?
result = model.most_similar(
    positive=["king", "woman"],
    negative=["man"],
    topn=1
)
print(result)  # → [('queen', 0.85)]

# Paris - France + Italy = ?
result2 = model.most_similar(
    positive=["paris", "italy"],
    negative=["france"],
    topn=1
)
print(result2) # → [('rome', 0.88)]

# doctor - man + woman = ?
result3 = model.most_similar(
    positive=["doctor", "woman"],
    negative=["man"],
    topn=1
)
print(result3) # → [('nurse', 0.85)]  ← reflects training data bias!

# analogy equations
# king − man + woman = queen
# paris − france + italy = rome
# walked − walk + run = ran

[('queen', 0.7698540687561035)]
[('rome', 0.8189547061920166)]
[('nurse', 0.7735227942466736)]


In [ ]:
# 8. Comparison: BoW vs TF-IDF vs Word Embeddings

# BoW — Simple word counts. No meaning. Sparse. Good for baseline models.
# TF-IDF — Weighted counts. Reduces common words. Still sparse. Better than BoW.
# Word2Vec / GloVe — Dense vectors. Captures meaning and relationships. Best quality.

# For modern NLP tasks, always prefer Word Embeddings or Transformer embeddings (BERT) over BoW/TF-IDF.


In [ ]:

# Feature	                BoW	                    TF-IDF	                 Embeddings
# Vector size	            vocab size (10k+)	    vocab size (10k+)	     50–300 fixed
# Sparsity	                very sparse	            very sparse	             dense
# Captures synonyms	        no	                    no	                     yes
# Word order	            ignored	                ignored	                 partial (W2V)
# Training data needed	    none (count-based)	    none (count-based)	     large corpus
# Interpretable	            yes — each dim = word	yes — each dim = word	 no (black box)
# Best for	                quick baseline	        search & retrieval	     most NLP tasks
# Use pre-trained?	        no	                    no	                     yes — free

# Start with TF-IDF as your baseline — it's fast and explainable.
# Switch to embeddings when you need semantic understanding, synonym handling, or better accuracy.
# For state-of-the-art, use BERT/sentence-transformers on top of embeddings.

# quick prototype - BoW
# search / ranking - TF-IDF
# classification / similarity - embeddings
# production NLP - sentence-transformers

In [ ]:
# Summary

# Loaded a pre-trained Word2Vec model.
# Found the most similar words to 'king', 'cricket', 'computer'.
# Performed analogy task: king - man + woman = ?
# Visualized word similarities in 2D using PCA (dimension reduction).
# Calculated sentence vectors using average of word embeddings.
