In [ ]:
#ANN
#Artificial neural network 

In [2]:
import numpy as np 
import pandas as pd 
import tensorflow as tf
tf.__version__

'2.21.0'

In [5]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:,3:-1].values 
y = dataset.iloc[:,-1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [6]:
#label encoding 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
#building the ANN

# Initializing the ANN
ann = tf.keras.models.Sequential()

In [11]:
#Adding the input layer and hidden layer 
ann.add(tf.keras.layers.Dense(units=7 , activation='relu'))

#second hidden layer
ann.add(tf.keras.layers.Dense(units=7 , activation='relu'))

#adding the output layer
ann.add(tf.keras.layers.Dense(units=1 , activation='sigmoid'))

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [15]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 110)

Epoch 1/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.8656 - loss: 0.3298
Epoch 2/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 470us/step - accuracy: 0.8645 - loss: 0.3297
Epoch 3/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.8634 - loss: 0.3294
Epoch 4/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.8644 - loss: 0.3297
Epoch 5/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step - accuracy: 0.8637 - loss: 0.3292
Epoch 6/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - accuracy: 0.8643 - loss: 0.3293
Epoch 7/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - accuracy: 0.8660 - loss: 0.3293
Epoch 8/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - accuracy: 0.8631 - loss: 0.3294
Epoch 9/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - accuracy: 0.8637 - loss: 0.3301
Epoch 10/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - accuracy: 0.8650 - loss: 0.3298
Epoch 11/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.8644 - loss: 0.3293
Epoch 12/110
250/25