In [1]:
import tensorflow as tf
tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.threading.set_inter_op_parallelism_threads(1)

In [2]:
#ANN
#Artificial neural network 

In [3]:
import numpy as np 
import pandas as pd 
import tensorflow as tf
tf.__version__

'2.21.0'

In [4]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:,3:-1].values 
y = dataset.iloc[:,-1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [5]:
#label encoding 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
#building the ANN

# Initializing the ANN
ann = tf.keras.models.Sequential()

In [10]:
#Adding the input layer and hidden layer 
ann.add(tf.keras.layers.Dense(units=7 , activation='relu'))

#second hidden layer
ann.add(tf.keras.layers.Dense(units=7 , activation='relu'))

#adding the output layer
ann.add(tf.keras.layers.Dense(units=1 , activation='sigmoid'))

In [11]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [12]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 110)

Epoch 1/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 547us/step - accuracy: 0.7295 - loss: 0.5687
Epoch 2/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - accuracy: 0.7976 - loss: 0.4669
Epoch 3/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - accuracy: 0.8035 - loss: 0.4391
Epoch 4/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step - accuracy: 0.8096 - loss: 0.4226
Epoch 5/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step - accuracy: 0.8149 - loss: 0.4116
Epoch 6/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - accuracy: 0.8246 - loss: 0.4003
Epoch 7/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.8317 - loss: 0.3896
Epoch 8/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - accuracy: 0.8403 - loss: 0.3782
Epoch 9/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.8460 - loss: 0.3679
Epoch 10/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.8518 - loss: 0.3597
Epoch 11/110
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step - accuracy: 0.8544 - loss: 0.3535
Epoch 12/110
250/25