In [2]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(4, activation = 'relu' , input_shape=(3,)),
    Dense(1, activation = 'sigmoid')
])

model.summary()

/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 4)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21 (84.00 B)

 Trainable params: 21 (84.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
import numpy as np

model = Sequential([
    Dense(4, activation = 'relu' , input_shape=(3,)),
    Dense(1, activation = 'sigmoid')
])

model.summary()

model.compile(optimizer='sgd' , loss='mse')

X_dummy = np.array([[1.0 , 2.0 , 3.0]])
y_dummy = np.array([[1.0]])

print("Weights BEFORE training:")
print(model.layers[0].get_weights()[0])

model.fit(X_dummy, y_dummy, epochs=1, verbose=0)

print("\nWeights AFTER training:")
print(model.layers[0].get_weights()[0])


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 4)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21 (84.00 B)

 Trainable params: 21 (84.00 B)

 Non-trainable params: 0 (0.00 B)

Weights BEFORE training:
[[ 0.8330947   0.3842063   0.8163674  -0.75161123]
 [ 0.8189266  -0.91529757 -0.5251591   0.43870294]
 [-0.34511143  0.77220297 -0.7071486  -0.5311549 ]]

Weights AFTER training:
[[ 0.83097124  0.38338688  0.8163674  -0.75161123]
 [ 0.8146797  -0.9169364  -0.5251591   0.43870294]
 [-0.3514818   0.76974475 -0.7071486  -0.5311549 ]]


In [7]:
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

value = 0.9
for layer in range(1, 11):
    value = sigmoid(value)
    print(f"After layer {layer}: {value:.6f}")

After layer 1: 0.710950
After layer 2: 0.670611
After layer 3: 0.661640
After layer 4: 0.659629
After layer 5: 0.659177
After layer 6: 0.659075
After layer 7: 0.659053
After layer 8: 0.659048
After layer 9: 0.659046
After layer 10: 0.659046


In [ ]:
import numpy as np

def relu(x):
    return np.maximum(0, x)


np.random.seed(1)
value = np.array([1.0])

for layer in range(1, 11):
    large_weight = np.random.uniform(5, 10)   
    value = relu(value * large_weight)
    print(f"After layer {layer}: {value}")

After layer 1: [7.08511002]
After layer 2: [60.94344156]
After layer 3: [304.75205978]
After layer 4: [1984.44267014]
After layer 5: [11378.35660985]
After layer 6: [62145.09034989]
After layer 7: [368601.2400727]
After layer 8: [2479876.76290597]
After layer 9: [17319056.0126375]
After layer 10: [1.33254266e+08]
