In [4]:
from PIL import Image
import numpy as np

image  = Image.open('images.jpeg')

image_array= np.array(image)
print("Image array shape:", image_array.shape)
print("Data type:", image_array.dtype)

Image array shape: (414, 738, 3)
Data type: uint8


In [ ]:
import numpy as np 

image = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 0],
    [7, 8, 9, 2, 1],
    [1, 0, 1, 3, 2],
    [0, 1, 2, 1, 4]
])

filter = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]

])

output = np.zeros((3,3))

for row in range(3):
    for col in range(3):
        patch = image[row:row+3, col:col+3]        
        output[row, col] = np.sum(patch * filter) 

print(output)


[[-6. 12. 16.]
 [-4.  7. 13.]
 [-4.  3.  5.]]


In [9]:
import numpy as np

def max_pool(image):
    h, w = image.shape
    output = np.zeros((h//2, w//2))  

    for row in range(0, h, 2):
        for col in range(0, w, 2):
            patch = image[row:row+2, col:col+2]   
            output[row//2, col//2] = np.max(patch)   

    return output

image = np.array([
    [1, 3, 2, 4],
    [5, 6, 1, 2],
    [7, 2, 9, 1],
    [0, 3, 5, 8]
])

print(max_pool(image))

[[6. 4.]
 [7. 9.]]


Instagram's face detection can find a face whether it's in the top-left corner of a photo or the center, because CNNs scan the SAME filter across every part of the image, not just one fixed spot. Similarly, Zomato's food recognition can identify a "pizza" whether it's photographed on the left or right side of the plate, since the convolution filter looks for the same pattern (round shape, cheese texture) everywhere in the image, not just one exact position.