In [ ]:
#multi-dimensional arrays

import numpy as np

arr2D = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr2D)
print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D , axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D , axis = 1)
print(sum_of_rows)

print(arr2D[0:2 , 1:2]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [ ]:
arr1 = np.zeros((3,4))
arr1.shape

arr2 = np.full((2,3) , 5)
print(arr2)

arr3 = np.eye(3)
print(arr3)

arr4 = np.arange(1,20)
print(arr4.shape)



[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(19,)


In [41]:
arr= np.array([1,2,3,4,5,6])
print(arr.shape)

reshaped = arr.reshape((2,3))
print(reshaped)

flatted  = reshaped.flatten()
print(flatted)

(6,)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
arr1D = np.array([1, 2, 3])
print(arr1D.ndim)



1
