In [2]:
import numpy as np
#task-1

ratings = np.array([
    [4, 3, 5, 2, 4],
    [3, 5, 4, 3, 2],
    [5, 4, 3, 5, 4],
    [2, 3, 4, 4, 5]
])

print(ratings[1:3])

[[3 5 4 3 2]
 [5 4 3 5 4]]


In [3]:
#task-2

steps = np.array([7500, 8200, 9000, 6800, 8500, 7200, 9300, 8100, 7600, 8800])
print(steps[steps>8000])

[8200 9000 8500 9300 8100 8800]


In [4]:
#task-3
ipl_scores = np.array([178, 156, 201, 169, 145, 188, 172, 210])
print(ipl_scores[[2, 5, 7]])

[201 188 210]


In [7]:
#task-4
prices = np.array([499,599,399,599,1999])
discounted = prices * 0.90
print(discounted)

[ 449.1  539.1  359.1  539.1 1799.1]


In [8]:
# Task 5 – Spotify Ratings (boolean masking)

song_ratings = np.array([3, -1, 5, 0, -2, 4, -3, 2])
song_ratings[song_ratings < 0] = 0
print(song_ratings)

[3 0 5 0 0 4 0 2]
