In [2]:
import numpy as np 

harsh = np.array([8000,10000,9000,8000])
raj = np.array([9000,8000,9800,10000])

print("Addition       :", harsh + raj)
print("Subtraction    :", harsh - raj)
print("Multiplication :", harsh * raj)
print("Division       :", (harsh / raj).round(2))


Addition       : [17000 18000 18800 18000]
Subtraction    : [-1000  2000  -800 -2000]
Multiplication : [72000000 80000000 88200000 80000000]
Division       : [0.89 1.25 0.92 0.8 ]


In [3]:
import numpy as np

A = np.array([[8, 3, 1],   # User preferences
              [2, 7, 5],
              [4, 4, 9]])

B = np.array([[9, 6, 3],   # Song popularity
              [5, 8, 4],
              [2, 4, 9]])

print(np.dot(A, B))      
print(np.matmul(A, B))   

[[ 89  76  45]
 [ 63  88  79]
 [ 74  92 109]]
[[ 89  76  45]
 [ 63  88  79]
 [ 74  92 109]]


In [12]:
import numpy as np 


image = np.array ([[120, 200,  85, 255],
                  [ 45, 178, 210,  90],
                  [230,  60, 145, 175],
                  [ 80, 195,  35, 220]])

print(image)  
print(image.T)
print(image.mean())
print(np.median(image))  
print(image.std().round(2))
print(image.var().round(2))          

[[120 200  85 255]
 [ 45 178 210  90]
 [230  60 145 175]
 [ 80 195  35 220]]
[[120  45 230  80]
 [200 178  60 195]
 [ 85 210 145  35]
 [255  90 175 220]]
145.1875
160.0
69.59
4843.03


In [17]:
import numpy as np 

grid = np.array([[4.5, 3.2, 2.8],
                 [3.2, 4.1, 3.6],
                 [2.8, 3.6, 4.3]])

print(np.linalg.det(grid).round(2))  
print(np.linalg.inv(grid).round(2))   

eigenvalues, eigenvectors = np.linalg.eig(grid)
print(eigenvalues.round(4))
print(eigenvectors.round(4))

9.35
[[ 0.5  -0.39  0.  ]
 [-0.39  1.23 -0.77]
 [ 0.   -0.77  0.88]]
[10.7028  1.6759  0.5213]
[[ 0.5648  0.7957  0.2188]
 [ 0.5889 -0.2029 -0.7823]
 [ 0.5781 -0.5707  0.5832]]


In [21]:
import numpy as np 

orders = np.array([[120, 95, 150, 200, 175, 130],
                   [ 80, 110, 140, 160, 120,  90]])

print(orders)   
print(orders.reshape(3,4))
print(orders.flatten())   

split = np.split(orders.flatten(),2)
print(split)

[[120  95 150 200 175 130]
 [ 80 110 140 160 120  90]]
[[120  95 150 200]
 [175 130  80 110]
 [140 160 120  90]]
[120  95 150 200 175 130  80 110 140 160 120  90]
[array([120,  95, 150, 200, 175, 130]), array([ 80, 110, 140, 160, 120,  90])]
