In [1]:
!pip install numpy


In [2]:
import numpy as np

In [8]:
#Task-2
follwers = np.array([12000,15000,56000,123000])
print(follwers.shape)
print(follwers.ndim)
print(follwers.dtype)


(4,)
1
int64


In [9]:
#task-3
order_ids = np.arange(101, 111)
print(order_ids)
print(order_ids.size)

[101 102 103 104 105 106 107 108 109 110]
10


In [17]:
#task-4
like_matrix = np.eye(3)
print(like_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#task-5
cricket_scores = np.array([45, 67, 120, 89, 54])
print(cricket_scores.itemsize)

8
